version: "3.8"

services:
  sse-server:
    build: .
    container_name: sse-server
    restart: always
    environment:
      - REDIS_URL=${REDIS_URL}
      - PORT=3007
    networks:
      - loopspa-network
      - dokploy-network   # <--- ADICIONEI AQUI (Conexão com a Internet/Dokploy)
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  loopspa-network:
    external: true
  dokploy-network:        # <--- ADICIONEI AQUI (Declaração da rede)
    external: true

